[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2018"
name = "binary-layout"
version = "0.1.0"
readme = "README.md"
documentation = "https://docs.rs/binary-layout"
homepage = "https://github.com/smessmer/binary-layout"
repository = "https://github.com/smessmer/binary-layout"
license = "MIT or Apache-2.0"
keywords = ["binary", "layout", "data", "structured", "format"]
categories = ["data-structures", "encoding", "memory-management", "network-programming"]

[dependencies]
doc-comment = "0.3.3"
paste = "1.0.5"

[dev-dependencies]
rand = "^0.8.1"
